import React from 'react';
import {registerRoot, Composition, AbsoluteFill, Sequence, useCurrentFrame, interpolate, Img, staticFile} from 'remotion';

const purple='#a88bfa', mint='#8ef0cf', ink='#10141f';
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'};
const font='Arial, "Noto Sans", sans-serif';
function Reveal({children,delay=0,style={}}){const f=useCurrentFrame();return <div style={{opacity:interpolate(f,[delay,delay+18],[0,1],clamp),transform:`translateY(${interpolate(f,[delay,delay+24],[28,0],clamp)}px)`,...style}}>{children}</div>}
function Heading({kicker,title,sub}){return <div style={{position:'absolute',left:110,top:110,width:760}}><Reveal><div style={{fontSize:22,letterSpacing:5,color:mint,marginBottom:28}}>{kicker}</div><div style={{fontSize:84,lineHeight:1.06,fontWeight:700,letterSpacing:-4}}>{title}</div></Reveal><Reveal delay={14}><div style={{fontSize:29,color:'#aeb7c9',lineHeight:1.55,marginTop:30,maxWidth:610}}>{sub}</div></Reveal></div>}
function Mark({d,delay=0,color=purple,width=12}){const f=useCurrentFrame();return <path d={d} fill="none" stroke={color} strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1-interpolate(f,[delay,delay+35],[0,1],clamp)}/>}
function Intro(){return <><Heading kicker="MEET LAYERPEN" title={<>Make your point.<br/><span style={{color:purple}}>Right on screen.</span></>} sub="A free, open-source annotation overlay for meetings, demos, and teaching."/><svg width="1920" height="1080" style={{position:'absolute'}}><Mark d="M112 362 Q435 410 799 371" delay={28}/></svg><Reveal delay={15} style={{position:'absolute',right:155,top:150,width:660,height:640,background:'#1c2234',borderRadius:38,transform:'rotate(-3deg)',padding:60,boxShadow:'0 40px 100px #0007'}}><div style={{fontSize:22,color:'#aeb7c9'}}>YOUR NEXT GREAT IDEA</div><div style={{fontSize:65,fontWeight:700,marginTop:55}}>Show it.<br/>Sketch it.<br/>Keep going.</div><svg width="570" height="200"><Mark d="M30 110 C80 5 245 10 240 100 C230 178 68 186 30 110 M270 110 L460 110 M422 73 L465 110 L422 148" delay={45} color={mint}/></svg></Reveal></>}
function Draw(){const f=useCurrentFrame();return <><Heading kicker="01 / DRAW ABOVE YOUR APPS" title={<>Less explaining.<br/><span style={{color:purple}}>More showing.</span></>} sub="Pen, highlighter, shapes, and whole-stroke erasing. Move and resize what you draw."/><div style={{position:'absolute',right:100,top:160,width:790,height:620,borderRadius:26,background:'#f3f4f7',color:ink,overflow:'hidden',boxShadow:'0 35px 90px #0007'}}><div style={{height:50,background:'#dfe3eb',padding:'15px 25px',fontSize:16}}>Example presentation · Illustration</div><div style={{padding:48}}><div style={{fontSize:34,fontWeight:700}}>From idea to launch</div><div style={{display:'flex',gap:25,marginTop:65}}>{['Explore','Build','Share'].map((x,i)=><div key={x} style={{width:190,height:135,borderRadius:18,background:['#ded8f4','#d5e8f4','#d6eee4'][i],display:'grid',placeItems:'center',fontSize:27,fontWeight:700}}>{x}</div>)}</div></div><svg width="790" height="540" style={{position:'absolute',top:50,left:0}}><Mark d="M274 235 C274 126 475 127 477 236 C481 344 265 338 274 235" delay={25}/><Mark d="M472 352 Q560 400 667 341 M639 329 L674 337 L662 374" delay={65} color="#7651d4"/></svg><div style={{position:'absolute',bottom:28,left:35,fontSize:18,color:'#68728a'}}>Switch to mouse mode to keep working.</div></div></>}
function Zoom(){const f=useCurrentFrame();const scale=interpolate(f,[30,80],[1,1.35],clamp);return <><Heading kicker="02 / FOCUS ON THE DETAIL" title={<>Zoom in.<br/><span style={{color:mint}}>Stay precise.</span></>} sub="Magnify a frozen region. Draw at the right scale, then return with your annotations intact."/><div style={{position:'absolute',right:115,top:160,width:720,height:600,overflow:'hidden',border:'2px solid #596079',borderRadius:28,background:'#1c2332'}}><div style={{transform:`scale(${scale})`,transformOrigin:'center',padding:80}}><div style={{color:'#8290a9',fontSize:20}}>EXAMPLE DETAIL</div><div style={{fontSize:160,fontWeight:700,marginTop:25,color:mint}}>2×</div><div style={{fontSize:30}}>A closer look.</div><svg width="580" height="180"><Mark d="M8 45 Q220 8 405 55" delay={85}/></svg></div><div style={{position:'absolute',bottom:22,left:30,color:'#aeb7c9',fontSize:18}}>Frozen screenshot zoom · Illustrated sequence</div></div></>}
function Languages(){const f=useCurrentFrame();const langs=['en','ja','zh-CN','ko'];const lang=langs[Math.min(3,Math.floor(f/45))];return <><Heading kicker="03 / MAKE IT YOURS" title={<>Your tools.<br/><span style={{color:purple}}>Your language.</span></>} sub="English, 한국어, 日本語, 简体中文. Customize shortcuts, colors, and your selected monitor."/><div style={{position:'absolute',right:185,top:90,height:780,width:733,display:'flex',justifyContent:'center'}}><Img src={staticFile(`settings-${lang}.png`)} style={{height:780,borderRadius:22,boxShadow:'0 30px 90px #0008'}}/></div><div style={{position:'absolute',right:265,top:895,fontSize:20,color:'#9ba8be'}}>Actual LayerPen settings interface</div></>}
function Export(){return <><Heading kicker="04 / KEEP THE MOMENT" title={<>Save the ink.<br/><span style={{color:mint}}>Share the idea.</span></>} sub="Export a screen PNG, a transparent ink layer, or a GIF replay of your annotations."/><div style={{position:'absolute',right:120,top:190,display:'flex',gap:28}}>{['PNG','GIF'].map((label,i)=><Reveal key={label} delay={i*15} style={{width:325,height:470,borderRadius:28,background:i?'#223b38':'#29233d',padding:40}}><div style={{fontSize:22,color:'#aeb7c9'}}>EXPORT</div><div style={{fontSize:82,fontWeight:700,marginTop:70,color:i?mint:purple}}>{label}</div><div style={{fontSize:24,lineHeight:1.5,marginTop:40}}>{i?'Annotation replay':'Screen or ink layer'}</div></Reveal>)}</div><div style={{position:'absolute',right:140,top:720,fontSize:20,color:'#9ba8be'}}>GIF replays ink over a static background; it is not screen recording.</div></>}
function End(){return <div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column'}}><Reveal><div style={{fontSize:28,letterSpacing:7,color:mint,textAlign:'center'}}>READY WHEN YOU ARE</div><div style={{fontSize:150,fontWeight:700,letterSpacing:-8,marginTop:35}}>Layer<span style={{color:purple}}>Pen</span></div></Reveal><Reveal delay={16}><div style={{fontSize:34,color:'#b5bfd2',textAlign:'center',marginTop:26}}>Windows installer + portable · v0.1.0</div><div style={{fontSize:30,color:'white',marginTop:55,padding:'22px 42px',border:'1px solid #61507e',borderRadius:50}}>github.com/BAEM1N/layerpen</div></Reveal><div style={{position:'absolute',bottom:105,fontSize:20,color:'#8894aa'}}>Free & open source · Windows x64 release · macOS/Linux validation pending</div></div>}
function Video(){const f=useCurrentFrame();return <AbsoluteFill style={{background:'radial-gradient(ellipse at 75% 20%, #25203c, #10141f 65%)',color:'#f9faff',fontFamily:font}}><div style={{position:'absolute',left:110,top:42,fontSize:20,fontWeight:700,letterSpacing:1}}>LayerPen <span style={{color:'#758197',fontWeight:400}}> / v0.1.0</span></div>{[Intro,Draw,Zoom,Languages,Export,End].map((C,i)=><Sequence key={i} from={i*180} durationInFrames={180}><C/></Sequence>)}<div style={{position:'absolute',bottom:40,left:110,right:110,height:2,background:'#343b4c'}}><div style={{width:`${f/1079*100}%`,height:'100%',background:purple}}/></div></AbsoluteFill>}
registerRoot(()=> <Composition id="LayerPenIntro" component={Video} durationInFrames={1080} fps={30} width={1920} height={1080}/>);
